### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by sils** [oxinabox/StackOverflowGitterNotifier.jl#3]
I added your requirements to `~/.julia/v0.4/REQUIRE` and did a `Pkg.resolve()` which is probably the wrong way to do it but it seemed to do the right thing - however it fails for me with:

```
...
INFO: Building HttpParser
ERROR: Build process failed.
 in build! at ./pkg/entry.jl:701
```

Sounds like an upstream problem?

Afterwards I can't run julia properly, just for completeness:

```
sobot@solar:~/StackOverflowGitterNotifier.jl$ julia src/stackoverflow2gitter.jl  SO http://www.stackoverflow.com julia-lang https://webhooks.gitter.im/e/...
ERROR: LoadError: write: broken pipe (EPIPE)
while loading /home/sobot/.julia/v0.4/Requests/src/Requests.jl, in expression starting on line 17
ERROR: LoadError: Failed to precompile Requests to /home/sobot/.julia/lib/v0.4/Requests.ji
 in compilecache at ./loading.jl:400
while loading /home/sobot/StackOverflowGitterNotifier.jl/src/stackoverflow2gitter.jl, in expression starting on line 1
```

**Comment by sils** [comment]
@oxinabox let me know if I can provide further info for debugging

**Comment by oxinabox** [comment]
Hi sils, I've just got back from holidays, sorry for the short delay in responding.

The normal way to install packages (such as the requirements for this),
is to run from the julia REPL: `Pkg.add(PKG_NAME)` for registered packages, and `Pkg.clone(PKG_GITHUB_URL)` for unregistered packages like this one.
rather than editing the `~/.julia/v0.4/REQUIRE` and running "Pkg.resolve"
which I am not exactly sure what that would do -- but I guess it should work,
though I am not sure if it would trigger 

So this repo, can be installed with all its dependencies by running  
from the julia repo: `Pkg.clone("https://github.com/oxinabox/StackOverflowGitterNotifier.jl")`
which should install it to `~/.julia/v0.4/StackOverflowGitterNotifier.jl'
I have added some install instructions to the readme.

You can just `rm -rf ~/.julia/v0.4` and then continue from step 2 of the instructions.

If you have issues, ping me on https://gitter.im/JuliaLang/julia
Or like anyone there should be able to help you install a package.

**Comment by sils** [comment]
```
julia> Pkg.clone("https://github.com/oxinabox/StackOverflowGitterNotifier.jl")
INFO: Initializing package repository /root/.julia/v0.4
 ...
INFO: Installing URIParser v0.1.6
ERROR: write: broken pipe (EPIPE)
 in uv_write at ./stream.jl:962
```

hm, I hope I'll find more time to investigate later.

**Comment by oxinabox** [comment]
Weird,
I suggest switching to julia 0.5, which is the current stable.
Seems like this is a julia issue, rather than an issue with just this package.
I think it might be an issue which is fixed in 0.5.
So if switching to julia 0.5 is an option, that would be my first place too look.

To help with further debugging could you run at the REPL:
`versioninfo()`
and paste the results?

**Comment by sils** [comment]
```
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.8
```

**Comment by oxinabox** [comment]
I'm going to close this because we have (out of stream) worked around what ever your issues may be.
And because I think it is either an unstream problem or perhaps a hosting problem.
Open an issue later if it reoccurs.
